<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lo Más Nuevo</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: #fff;
            padding: 20px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
            border-radius: 8px;
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
            color: #333;
        }
        .filter {
            margin-bottom: 20px;
        }
        .new-item {
            display: flex;
            margin: 10px 0;
            border-radius: 5px;
            padding: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            align-items: center;
            position: relative;
        }
        .new-item img {
            max-width: 150px;
            max-height: 200px;
            border-radius: 5px;
            margin-right: 15px;
            object-fit: cover;
        }
        .new-item h2 {
            margin: 0 0 10px;
            color: #007bff;
        }
        .new-item p {
            margin: 0;
            color: #555;
        }
        .status {
            font-weight: bold;
            margin-top: 5px;
        }
        button {
            padding: 10px;
            margin-top: 20px;
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            width: 100%;
        }
        button:hover {
            background-color: #218838;
        }
        form {
            margin-top: 20px;
            display: flex;
            flex-direction: column;
        }
        input[type="text"], input[type="number"], select {
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        input[type="submit"] {
            padding: 10px;
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #218838;
        }
        .resolved {
            background-color: #d4edda;
        }
        .in-progress {
            background-color: #fff3cd;
        }
        .not-assigned {
            background-color: #e9e9e9;
        }
        .rejected {
            background-color: #f8d7da;
        }
        .observation {
            display: none;
            margin-top: 10px;
            font-style: italic;
            color: red;
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Lo Más Nuevo</h1>

    <div class="filter">
        <label for="filter-type">Filtrar por tipo:</label>
        <select id="filter-type">
            <option value="all">Todo</option>
            <option value="pelicula">Películas</option>
            <option value="serie">Series</option>
        </select>
    </div>

    <div id="new-items-section">
        <!-- Aquí se agregarán los nuevos pedidos -->
    </div>

    <button onclick="toggleForm()">Agregar nuevo contenido</button>

    <form id="new-item-form" style="display: none;">
        <h2>Agregar nuevo contenido</h2>
        <input type="text" id="user-name" placeholder="Tu nombre" required>
        <select id="item-type" required>
            <option value="">Seleccione tipo</option>
            <option value="pelicula">Película</option>
            <option value="serie">Serie</option>
        </select>
        <input type="text" id="item-title" placeholder="Título del nuevo contenido" required>
        <input type="number" id="item-year" placeholder="Año de lanzamiento" required>
        <input type="text" id="item-genre" placeholder="Género" required>
        <input type="text" id="item-image" placeholder="URL de la imagen" required>
        <input type="submit" value="Agregar">
    </form>
</div>

<script>
    function toggleForm() {
        const form = document.getElementById('new-item-form');
        form.style.display = form.style.display === 'none' ? 'flex' : 'none';
    }

    document.getElementById('new-item-form').addEventListener('submit', function(event) {
        event.preventDefault();

        const userName = document.getElementById('user-name').value;
        const type = document.getElementById('item-type').value;
        const title = document.getElementById('item-title').value;
        const year = document.getElementById('item-year').value;
        const genre = document.getElementById('item-genre').value;
        const image = document.getElementById('item-image').value;

        const newItem = document.createElement('div');
        newItem.className = 'new-item not-assigned';
        newItem.setAttribute('data-type', type);

        newItem.innerHTML = `
            <img src="${image}" alt="Imagen de la película/serie">
            <div>
                <h2>${title} (${type})</h2>
                <p>Año: ${year}</p>
                <p>Género: ${genre}</p>
                <p>Solicitado por: ${userName}</p>
                <div class="status">Estado: No asignado</div>
                <button onclick="markAsInProgress(this)">Marcar como en proceso</button>
                <button onclick="rejectItem(this)">Rechazar</button>
                <div class="observation">Observación: <span class="text"></span></div>
            </div>
        `;

        document.getElementById('new-items-section').appendChild(newItem);

        // Limpiar el formulario
        document.getElementById('user-name').value = '';
        document.getElementById('item-type').value = '';
        document.getElementById('item-title').value = '';
        document.getElementById('item-year').value = '';
        document.getElementById('item-genre').value = '';
        document.getElementById('item-image').value = '';

        document.getElementById('new-item-form').style.display = 'none';

        filterItems();
    });

    document.getElementById('filter-type').addEventListener('change', filterItems);

    function filterItems() {
        const filter = document.getElementById('filter-type').value;
        const items = document.querySelectorAll('.new-item');

        items.forEach(item => {
            if (filter === 'all' || item.getAttribute('data-type') === filter) {
                item.style.display = 'flex'; // Mostrar
            } else {
                item.style.display = 'none'; // Ocultar
            }
        });
    }

    // Función para marcar como en proceso
    function markAsInProgress(button) {
        const password = prompt("Introduce la contraseña para cambiar el estado:");
        const item = button.parentElement.parentElement;

        if (password === "148233") {
            const statusText = item.querySelector('.status');

            if (item.classList.contains('not-assigned')) {
                item.classList.remove('not-assigned');
                item.classList.add('in-progress'); // Cambiar a estado en proceso
                statusText.innerHTML = "Estado: En proceso"; // Actualizar estado
                item.style.backgroundColor = "#fff3cd"; // Color amarillo
                alert("Pedido marcado como en proceso.");
            } else {
                alert("Este pedido ya está en proceso.");
            }
        } else {
            alert("Contraseña incorrecta.");
        }
    }

    // Función para rechazar
    function rejectItem(button) {
        const password = prompt("Introduce la contraseña para rechazar el pedido:");
        const item = button.parentElement.parentElement;

        if (password === "148233") {
            const observation = prompt("Escribe una observación para el rechazo:");
            item.classList.remove('not-assigned', 'in-progress');
            item.classList.add('rejected'); // Cambiar a estado rechazado
            item.querySelector('.status').innerHTML = "Estado: Rechazado"; // Actualizar estado
            item.style.backgroundColor = "#f8d7da"; // Color rojo claro
            item.querySelector('.observation .text').textContent = observation; // Mostrar observación
            item.querySelector('.observation').style.display = 'block'; // Mostrar observación
            alert("Pedido rechazado.");
        } else {
            alert("Contraseña incorrecta.");
        }
    }
</script>
</body>
</html>
